services:
  pettrack:
    build: .
    container_name: pettrack
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./pettrack_server/replays:/app/replays
      - ./pettrack_server/captured_images:/app/captured_images
      - ./pettrack_server/pettrack.db:/app/pettrack.db
      - ./pettrack_server/.env:/app/.env
